### ISSUE TITLE
Método [ProcedimentoAndamentoRN.gravarLogDebug] não encontrado

### ISSUE THREAD

**Issue by guilhermeadc** [spbgovbr/mod-sei-pen#10]
Reportado recusa de recebimento de processo contendo a serguinte mensagem de erro:
Método [ProcedimentoAndamentoRN.gravarLogDebug] não encontrado.

Descrição: Método [ProcedimentoAndamentoRN.gravarLogDebug] não encontrado. Mensagem: Método [ProcedimentoAndamentoRN.gravarLogDebug] não encontrado.
Trilha de Processamento:
#0 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(72): InfraRN->_call('sinalizarInicio...', Array)
#1 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(72): ProcedimentoAndamentoRN->sinalizarInicioRecebimento(Array)
#2 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(185): ReceberProcedimentoRN->receberProcedimento(141309)
#3 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(379): ProcessarPendenciasRN->receberProcedimento('141309')
#4 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(353): PendenciasTramiteRN->enviarPendenciaProcessamentoDireto(Object(PendenciaDTO))
#5 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(103): PendenciasTramiteRN->enviarPendenciaProcessamento(Object(PendenciaDTO), false)
#6 /opt/sei/scripts/mod-pen/MonitoramentoTarefasPEN.php(45): PendenciasTramiteRN->encaminharPendencias(false, false, false)
#7 {main} Trilha de Processamento Original: \n0 /opt/sei/web/modulos/pen/rn/ProcedimentoAndamentoRN.php(120): InfraRN->call('gravarLogDebug', Array)
\n1 /opt/sei/web/modulos/pen/rn/ProcedimentoAndamentoRN.php(120): ProcedimentoAndamentoRN->gravarLogDebug('Tr\xE2mite de rece...', 3)
\n2 [internal function]: ProcedimentoAndamentoRN->sinalizarInicioRecebimentoControlado(Array)
\n3 /opt/infra/infra_php/InfraRN.php(140): call_user_func(Array, Array)
\n4 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(72): InfraRN->_call('sinalizarInicio...', Array)
\n5 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(72): ProcedimentoAndamentoRN->sinalizarInicioRecebimento(Array)
\n6 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(185): ReceberProcedimentoRN->receberProcedimento(141309)
\n7 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(379): ProcessarPendenciasRN->receberProcedimento('141309')
\n8 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(353): PendenciasTramiteRN->enviarPendenciaProcessamentoDireto(Object(PendenciaDTO))
\n9 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(103): PendenciasTramiteRN->enviarPendenciaProcessamento(Object(PendenciaDTO), false)
\n10 /opt/sei/scripts/mod-pen/MonitoramentoTarefasPEN.php(45): PendenciasTramiteRN->encaminharPendencias(false, false, false) \n11
{main}

**Comment by guilhermeadc** [comment]
Problema já resolvido na release 2.0.1, duplicado de Issue #7 .
