### ISSUE TITLE
Erro no agendamento módulo PEN de Hipóteses Legais

### ISSUE THREAD

**Issue by guilhermeadc** [spbgovbr/mod-sei-pen#146]
**Descreva o erro**
Erro registrado no agendamento de tarefas do SEI durante a sincronização de hipóteses legais do PEN. Os detalhes do erro estão descritos no log abaixo.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para a página de agendamento de tarefas do SEI
2. Execute o agendamento "PENAgendamentoRN->atualizarHipotesesLegaisControlado"
3. Veja o erro de sincronização: Erro no agendamento das Hipóteses Legais

-----

**Comportamento esperado**
Esperado que a sincronização ocorra com sucesso.

-----

**Screenshots**
N/A

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do módulo: 3.1.12
 - Navegador: N/A
 - Perfil do Usuário: N/A

-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
```
Comando: PENAgendamentoRN::atualizarInformacoesPEN()

Erro: Descrição:
Erro no agendamento das Hipóteses Legais

Mensagem:
Erro no agendamento das Hipóteses Legais

Trilha de Processamento:
#0 /opt/appsei/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(621): InfraRN->__call('atualizarInform...', Array)
#1 /opt/appsei/infra/infra_php/InfraAgendamentoTarefa.php(198): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#2 /opt/appsei/sei/scripts/AgendamentoTarefaSEI.php(27): InfraAgendamentoTarefa->executar('naoresponda_sei...', 'neijobson@anate...')
#3 {main}

Descrição Original:
Exception: 'Warning: /opt/appsei/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php linha:120.
Use of undefined constant SOAP_1_1 - assumed 'SOAP_1_1' (this will throw an Error in a future version of PHP) ' in /opt/appsei/infra/infra_php/Infra.php:205
Stack trace:
#0 /opt/appsei/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php(120): infraGerarExcecao(2, 'Use of undefine...', '/opt/appsei/sei...', 120, Array)
#1 /opt/appsei/sei/web/modulos/pen/rn/PENAgendamentoRN.php(21): ProcessoEletronicoRN->__construct()
#2 /opt/appsei/infra/infra_php/InfraRN.php(138): PENAgendamentoRN->atualizarHipotesesLegaisControlado()
#3 /opt/appsei/sei/web/modulos/pen/rn/PENAgendamentoRN.php(156): InfraRN->__call('atualizarHipote...', Array)
#4 /opt/appsei/infra/infra_php/InfraRN.php(140): PENAgendamentoRN->atualizarInformacoesPENControlado(Array)
#5 /opt/appsei/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(621): InfraRN->__call('atualizarInform...', Array)
#6 /opt/appsei/infra/infra_php/InfraAgendamentoTarefa.php(198): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#7 /opt/appsei/sei/scripts/AgendamentoTarefaSEI.php(27): InfraAgendamentoTarefa->executar('naoresponda_sei...', 'neijobson@anate...')
#8 {main}

Trilha de Processamento Original:
\n0 /opt/appsei/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php(120): infraGerarExcecao(2, 'Use of undefine...', '/opt/appsei/sei...', 120, Array)
\n1 /opt/appsei/sei/web/modulos/pen/rn/PENAgendamentoRN.php(21): ProcessoEletronicoRN->__construct()
\n2 /opt/appsei/infra/infra_php/InfraRN.php(138): PENAgendamentoRN->atualizarHipotesesLegaisControlado()
\n3 /opt/appsei/sei/web/modulos/pen/rn/PENAgendamentoRN.php(156): InfraRN->__call('atualizarHipote...', Array)
\n4 /opt/appsei/infra/infra_php/InfraRN.php(140): PENAgendamentoRN->atualizarInformacoesPENControlado(Array)
\n5 /opt/appsei/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(621): InfraRN->__call('atualizarInform...', Array)
\n6 /opt/appsei/infra/infra_php/InfraAgendamentoTarefa.php(198): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
\n7 /opt/appsei/sei/scripts/AgendamentoTarefaSEI.php(27): InfraAgendamentoTarefa->executar('naoresponda_sei...', 'neijobson@anate...')
\n8 {main}
```

**Comment by caduvieira** [comment]
Erro no super 4.0.3.1?

**Comment by guilhermeadc** [comment]
> Erro no super 4.0.3.1?

Erro no módulo de Barramento do PEN para o SEI.

**Comment by guilhermeadc** [comment]
Aparentemente, problema ocorria por falta de extensão SOAP no PHP. Demanda será fechada até confirmação da correta instalação das extensões pelo usuário.
